services:
  chat:
    build:
      context: ./api
    container_name: chat
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.chatapi.rule=Host(`chat.marcel.co.nz`)"
        - "traefik.http.routers.chatapi.entrypoints=websecure"
        - "traefik.http.routers.chatapi.tls=true"
        - "traefik.http.routers.chatapi.tls.certresolver=myresolver"
        - "traefik.http.services.chatapi.loadbalancer.server.port=8000"
        
        - "traefik.http.middlewares.chatapi-ratelimit.ratelimit.average=10"
        - "traefik.http.middlewares.chatapi-ratelimit.ratelimit.burst=20"

        - "traefik.http.middlewares.chatapi-buffer.buffering.maxRequestBodyBytes=5242880"

        - "traefik.http.routers.chatapi.middlewares=chatapi-ratelimit,chatapi-buffer"
    networks:
      - proxy

  db:
    image: postgres:18
    container_name: postgres_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - proxy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - proxy


volumes:
  postgres_data:
  pgadmin_data:

networks:
  proxy:
    external: true
