"""change_to_receiver_id

Revision ID: 88909dd7c120
Revises: 25641ae53626
Create Date: 2026-01-02 14:15:44.291135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88909dd7c120'
down_revision: Union[str, Sequence[str], None] = '25641ae53626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_requests', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_friend_request_pair'), 'friend_requests', type_='unique')
    op.create_unique_constraint('uq_friend_request_pair', 'friend_requests', ['sender_id', 'receiver_id'])
    op.drop_constraint(op.f('friend_requests_user_id_2_fkey'), 'friend_requests', type_='foreignkey')
    op.drop_constraint(op.f('friend_requests_user_id_1_fkey'), 'friend_requests', type_='foreignkey')
    op.create_foreign_key(None, 'friend_requests', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.drop_column('friend_requests', 'user_id_2')
    op.drop_column('friend_requests', 'user_id_1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend_requests', sa.Column('user_id_1', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('friend_requests', sa.Column('user_id_2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'friend_requests', type_='foreignkey')
    op.create_foreign_key(op.f('friend_requests_user_id_1_fkey'), 'friend_requests', 'users', ['user_id_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('friend_requests_user_id_2_fkey'), 'friend_requests', 'users', ['user_id_2'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_friend_request_pair', 'friend_requests', type_='unique')
    op.create_unique_constraint(op.f('uq_friend_request_pair'), 'friend_requests', ['user_id_1', 'user_id_2'], postgresql_nulls_not_distinct=False)
    op.drop_column('friend_requests', 'receiver_id')
    # ### end Alembic commands ###
